fix: github 서버 원격 pull 정책

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,7 +27,9 @@ jobs:
 
             echo "Updating repository..."
             cd /srv/portfolio
-            sudo git pull origin main || { echo "Git pull failed"; exit 1; }
+            echo "Resetting repository to match origin/main..."
+            sudo git fetch origin main || { echo "Git fetch failed"; exit 1; }
+            sudo git reset --hard origin/main || { echo "Git reset failed"; exit 1; }
 
             echo "Setting up Node.js environment..."
             export NVM_DIR="$HOME/.nvm"
