refactor: main branch change

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,9 +1,9 @@
-name: Deploy on Master Merge
+name: Deploy on Main Merge
 
 on:
     push:
         branches:
-            - master
+            - main
         paths-ignore:
             - 'README.md'
 
@@ -16,7 +16,7 @@ jobs:
               uses: actions/checkout@v4
 
             - name: Execute remote ssh and Deploy
-              uses: appleboy/ssh-action@master
+              uses: appleboy/ssh-action@main
               with:
                   host: ${{ secrets.SSH_HOST }}
                   username: ${{ secrets.SSH_USERNAME }}
@@ -27,7 +27,7 @@ jobs:
 
                       echo "Updating repository..."
                       cd /srv/portfolio
-                      sudo git pull origin master || { echo "Git pull failed"; exit 1; }
+                      sudo git pull origin main || { echo "Git pull failed"; exit 1; }
 
                       echo "Setting up Node.js environment..."
                       export NVM_DIR="$HOME/.nvm"
